#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("S00144297MobileDev.Resource", IsApplication=true)]

namespace S00144297MobileDev
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fadeIn = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fadeOut = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slideLeft = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slideRight = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int SportList = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int TownList = 2131099649;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AppLogo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int buttonshapeBlue = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int buttonshapeGreen = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int buttonshapeOrange = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int buttonshapeRed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int calendar = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int delete = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int DoubleChevronRight = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int edit = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int editText_style = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int email = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int home = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int hourglass = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int imgFind = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int imgHome = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int imgPlus = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int imgUser = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int location = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int phone = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int search = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int selector = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Spinner_style = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int user = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080017
			public const int btnEditPostSave = 2131230743;
			
			// aapt resource value: 0x7f080012
			public const int btnEditPostTime = 2131230738;
			
			// aapt resource value: 0x7f080025
			public const int btnMainLogIn = 2131230757;
			
			// aapt resource value: 0x7f080027
			public const int btnMainRegister = 2131230759;
			
			// aapt resource value: 0x7f080036
			public const int btnNewPostCreate = 2131230774;
			
			// aapt resource value: 0x7f080030
			public const int btnNewPostDate = 2131230768;
			
			// aapt resource value: 0x7f080031
			public const int btnNewPostTime = 2131230769;
			
			// aapt resource value: 0x7f080045
			public const int btnRRegister = 2131230789;
			
			// aapt resource value: 0x7f080047
			public const int btnRSignIn = 2131230791;
			
			// aapt resource value: 0x7f08004d
			public const int btnSearch = 2131230797;
			
			// aapt resource value: 0x7f080011
			public const int dpEditPostDate = 2131230737;
			
			// aapt resource value: 0x7f08001e
			public const int imgEdit = 2131230750;
			
			// aapt resource value: 0x7f08001c
			public const int imgListViewHomeArrow = 2131230748;
			
			// aapt resource value: 0x7f080020
			public const int imgLogin = 2131230752;
			
			// aapt resource value: 0x7f080001
			public const int imgNavHome = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int imgNavSearch = 2131230724;
			
			// aapt resource value: 0x7f08000a
			public const int imgNavUser = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int imgNewPost = 2131230727;
			
			// aapt resource value: 0x7f08001f
			public const int imgRemove = 2131230751;
			
			// aapt resource value: 0x7f08003a
			public const int imgTime = 2131230778;
			
			// aapt resource value: 0x7f08000c
			public const int linearlayoutEditPost = 2131230732;
			
			// aapt resource value: 0x7f080018
			public const int linearlayoutHome = 2131230744;
			
			// aapt resource value: 0x7f080028
			public const int linearlayoutMyProfile = 2131230760;
			
			// aapt resource value: 0x7f08002b
			public const int linearlayoutNewPost = 2131230763;
			
			// aapt resource value: 0x7f080037
			public const int linearlayoutPostDetails = 2131230775;
			
			// aapt resource value: 0x7f080048
			public const int linearlayoutSearch = 2131230792;
			
			// aapt resource value: 0x7f08004e
			public const int linearlayoutSearchResults = 2131230798;
			
			// aapt resource value: 0x7f080050
			public const int listViewTest = 2131230800;
			
			// aapt resource value: 0x7f08001d
			public const int listViewTitle = 2131230749;
			
			// aapt resource value: 0x7f080010
			public const int lstEditPostSport = 2131230736;
			
			// aapt resource value: 0x7f080014
			public const int lstEditPostTown = 2131230740;
			
			// aapt resource value: 0x7f080019
			public const int lstHomeItems = 2131230745;
			
			// aapt resource value: 0x7f08002f
			public const int lstNewPostSport = 2131230767;
			
			// aapt resource value: 0x7f080033
			public const int lstNewPostTown = 2131230771;
			
			// aapt resource value: 0x7f08004f
			public const int lstSearchResults = 2131230799;
			
			// aapt resource value: 0x7f08004b
			public const int lstSearchSports = 2131230795;
			
			// aapt resource value: 0x7f08004c
			public const int lstSearchTowns = 2131230796;
			
			// aapt resource value: 0x7f08002a
			public const int lstUserPosts = 2131230762;
			
			// aapt resource value: 0x7f080000
			public const int navHome = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int navNewPost = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int navSearch = 2131230723;
			
			// aapt resource value: 0x7f080009
			public const int navUser = 2131230729;
			
			// aapt resource value: 0x7f080013
			public const int tbxEditPostAddress = 2131230739;
			
			// aapt resource value: 0x7f080016
			public const int tbxEditPostContactEmail = 2131230742;
			
			// aapt resource value: 0x7f080015
			public const int tbxEditPostContactNumber = 2131230741;
			
			// aapt resource value: 0x7f08000f
			public const int tbxEditPostDetails = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int tbxEditPostTitle = 2131230734;
			
			// aapt resource value: 0x7f080021
			public const int tbxLoginEmail = 2131230753;
			
			// aapt resource value: 0x7f080023
			public const int tbxLoginPassword = 2131230755;
			
			// aapt resource value: 0x7f080032
			public const int tbxNewPostAddress = 2131230770;
			
			// aapt resource value: 0x7f080035
			public const int tbxNewPostContactEmail = 2131230773;
			
			// aapt resource value: 0x7f080034
			public const int tbxNewPostContactNumber = 2131230772;
			
			// aapt resource value: 0x7f08002e
			public const int tbxNewPostDetails = 2131230766;
			
			// aapt resource value: 0x7f08002d
			public const int tbxNewPostTitle = 2131230765;
			
			// aapt resource value: 0x7f080044
			public const int tbxRegisterConfirmPassword = 2131230788;
			
			// aapt resource value: 0x7f080040
			public const int tbxRegisterEmail = 2131230784;
			
			// aapt resource value: 0x7f080042
			public const int tbxRegisterPassword = 2131230786;
			
			// aapt resource value: 0x7f08004a
			public const int tbxSearch = 2131230794;
			
			// aapt resource value: 0x7f080002
			public const int textView1 = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int textView2 = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int textView3 = 2131230728;
			
			// aapt resource value: 0x7f08000b
			public const int textView4 = 2131230731;
			
			// aapt resource value: 0x7f08003f
			public const int txPostDetailsAddress = 2131230783;
			
			// aapt resource value: 0x7f08003c
			public const int txPostDetailsDate = 2131230780;
			
			// aapt resource value: 0x7f080039
			public const int txPostDetailsDetails = 2131230777;
			
			// aapt resource value: 0x7f08003e
			public const int txPostDetailsEmail = 2131230782;
			
			// aapt resource value: 0x7f08003d
			public const int txPostDetailsPhone = 2131230781;
			
			// aapt resource value: 0x7f08003b
			public const int txPostDetailsTime = 2131230779;
			
			// aapt resource value: 0x7f080038
			public const int txPostDetailsTitle = 2131230776;
			
			// aapt resource value: 0x7f08000d
			public const int txtEditPostHeading = 2131230733;
			
			// aapt resource value: 0x7f08001b
			public const int txtHomeSubTitle = 2131230747;
			
			// aapt resource value: 0x7f08001a
			public const int txtHomeTitle = 2131230746;
			
			// aapt resource value: 0x7f080022
			public const int txtLoginEmailValidation = 2131230754;
			
			// aapt resource value: 0x7f080024
			public const int txtLoginPasswordValidation = 2131230756;
			
			// aapt resource value: 0x7f080029
			public const int txtMyPostsHeading = 2131230761;
			
			// aapt resource value: 0x7f08002c
			public const int txtNewPostHeading = 2131230764;
			
			// aapt resource value: 0x7f080026
			public const int txtRegister = 2131230758;
			
			// aapt resource value: 0x7f080041
			public const int txtRegisterEmailValidation = 2131230785;
			
			// aapt resource value: 0x7f080043
			public const int txtRegisterPasswordValidation = 2131230787;
			
			// aapt resource value: 0x7f080049
			public const int txtSearchHeading = 2131230793;
			
			// aapt resource value: 0x7f080046
			public const int txtSignIn = 2131230790;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_bar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditPost = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HomeListViewRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int listViewRow = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MyProfile = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NewPost = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PostDetails = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Register = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Search = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SearchResult = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Test = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int BackgroundColor = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int GoogleKey = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int CustomActionBarTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MyActionBar = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
